## ================= Search =================
# the fields to return in search results from a solr query
# ontology search: if you define a value, ensure ontologyType is also included
search:
  external:
    filterConfigs:
      - signature: descendants,evidenceCode,evidenceCodeUsageRelationships
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c2:8082",
          resourceFormat: "/ontology/eco/terms/{evidenceCode}/descendants?relations={evidenceCodeUsageRelationships}",
          responseClass: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.model.OntologyDescendants",
          responseConverter: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.converter.DescendantsFilterConverter"
        }
      - signature: descendants,goId,goUsageRelationships
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c2:8082",
          resourceFormat: "/QuickGO/services/go/terms/{goId}/descendants?relations={goUsageRelationships}",
          responseClass: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.model.OntologyDescendants",
          responseConverter: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.converter.DescendantsFilterConverter"
        }
      - signature: goId,goUsageRelationships,slim
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c2:8082",
          resourceFormat: "/QuickGO/services/go/terms/{goId}/descendants?relations={goUsageRelationships}",
          responseClass: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.model.OntologyDescendants",
          responseConverter: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.converter.SlimmingFilterConverter"
        }
model:
  repo-to-domain-field-name-transformations:
    transformations: {
      goId_join: goId
    }
annotation:
  validation:
    validationResource: /nfs/public/rw/goa/quickgo_origin/full/DB_XREFS_ENTITIES.dat.gz
    chunk: 30
    headerLines: 1
    reference_dbs:
      - pmid
      - doi
      - go_ref
      - reactome
  download:
    taskExecutor:
      corePoolSize: 4
      maxPoolSize: 8
      queueCapacity: 100
      keepAliveSeconds: 7200
      allowCoreThreadTimeout: true
      waitForTasksToCompleteOnShutdown: false
    ontologySource: ONTOLOGY_IRI.dat.gz
  terms:
      query:
        compatible:
          fields: ['assignedBy', 'evidenceCode', 'goEvidence', 'goId', 'dbSubset', 'geneProductType', 'qualifier',
          'targetSet', 'taxonId', 'geneProductId']


